### ISSUE TITLE
The link to "See the list of available provisioning locations and data centers" is broken

### ISSUE THREAD

**Issue by jesusmah** [ibm-cloud-docs/cloud-foundry#42]
The link drives you to https://cloud.ibm.com/catalog/docs/cloud-foundry/index.html#provisioning-targets which is a broken link.

**Comment by vanadiscrawford** [comment]
Thank you for your comments.  Cloud Foundry Enterprise Environment has been deprecated and no additional documentation updates will be made at this time.
