### ISSUE TITLE
Eclipse Tools are GONE - why do we still point at them?

### ISSUE THREAD

**Issue by patmc2go** [ibm-cloud-docs/cloud-foundry#43]
Need to understand how we can get this doc page fixed.  The implied question is really _Who is in charge of the technical message that caused this doc page to get created_.

There are really three pages, but they all look the same, you’ll find them with this search 
> https://cloud.ibm.com/docs/search/eclipse%20tools

These are those pages:
- https://cloud.ibm.com/docs/starters?topic=starters-developing-with-eclipse-tools
- https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-starter-eclipse
- https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-starter-eclipse

I’ve chased this for a while as I’ve had a support ticket about this for months (`CS0119176: Page reference gives "Page not found" error`), you may have noticed a couple rounds of FEEDBACK entries I’d created about this, when there would be doc pages shown that were empty.   That issue seems resolved, but the pages that still exist are not quite right either:
- the pages all seem to have the same content, the URL used to get there varies.
- the problem on the page has two aspects - _bad content/message_ and _bad external link_.

**Re: bad content/message**
- I doubt that the listed version of Eclipse is still the best recommended version given where our Liberty buildpack is (WRT the Java version used and all)
- The page talks about something that does not exist anymore, by any name [Bluemix Tools for Eclipse | IBM® Eclipse Tools for IBM Cloud]
- The screenshot has the old names, I think it was taken with the old Bluemix branded tool version given server type is shown as IBM Bluemix.

**Re: bad link issue:**
- this is the link on that page: http://marketplace.eclipse.org/marketplace-client-intro?mpc_install=1774120  - the ID 1774120 is to the package that is gone: IBM Eclipse Tools for IBM Cloud
- the true target does not exist anymore;  the link to the first landing page works, but the implied goal of the link is to get something from that site that is gone.  The landing page points to https://marketplace.eclipse.org/content/ibm-eclipse-tools-ibm-cloud and that gets a `403` once you are logged in.
- there may be alternatives to the original target, but we’d need the owner of the technical message to confirm that is the goal, and identify the correct targets for the goal:
> An appropriate Eclipse-based IDE that can support development and deployment of Liberty applications on the Cloud Foundry runtime platform provided by the IBM Cloud.

Not clear what the right fix is, it could be _Delete this page_ or _Make it current by identifying the right answer for the recommended Eclipse IDE version/package and any appropriate tools_ - this is where we need the _owner of the technical message_ (if such a person exists anymore).

**Comment by jgwest** [comment]
Hi @patmc2go , my team was responsible for this product, which is long since deprecated and out of support. We previously removed this page from the docs repo in 2018 (IIRC) for this exact reason.

BUT, it looks like this page was incorrectly reintroduced by this commit:
```
3792804e820f3be726aeb6c95a8ff5a52aa36443 is the first bad commit
commit 3792804e820f3be726aeb6c95a8ff5a52aa36443
Author: Samuel Jessee <Samuel.Jessee@ibm.com>
Date:   Fri Aug 30 11:11:35 2019 -0400
```

I can safely say this page should be deleted again.

**Comment by Samuel-Jessee-1BM** [comment]
This is now fixed in our working repo and I'm working on getting it published to prod. See: https://github.ibm.com/cloud-docs/cloud-foundry/pull/308.
