### ISSUE TITLE
Availability Monitoring does not support the ability to monitor CF apps in CFEE

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/cloud-foundry#44]
As described in the doc, the service Availability Monitoring does not support the ability to monitor CF apps running in CFEE. You cannot bind apps running in CFEE from Availability Monitoring located in public org/space. Plus, Availability Monitoring is not hosted in Frankfurt.

This section below should be removed from the doc:
https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-management-enablement#monitoring-applications

**Comment by vanadiscrawford** [comment]
Thank you for your comments.  Cloud Foundry Enterprise Environment has been deprecated and no additional documentation updates will be made at this time.
