### ISSUE TITLE
Does a private hosting model of CF offerings still exist?

### ISSUE THREAD

**Issue by EunKyung-Kim** [ibm-cloud-docs/cloud-foundry#46]
Hi,

I found out that there is a private hosting model of CF offerings as followings.
[https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-what-is-cloud-foundry#ibmcf-offerings](url)
It describes it is an **on-premises** Cloud Foundry platform that runs in your data-center on your infrastructure, giving the highest level of isolation security for your application hosting.

Is its hosting model still provided?

**Comment by vanadiscrawford** [comment]
Thank you for your comments.  Cloud Foundry Enterprise Environment has been deprecated and no additional documentation updates will be made at this time.
