### ISSUE TITLE
Broken link to CF Env Dashboard

### ISSUE THREAD

**Issue by arnhyndman** [ibm-cloud-docs/cloud-foundry#53]
The first link on https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-create_orgs docs page is broken. 

https://cloud.ibm.com/dashboard/cloudfoundry?filter=cf_environments is not the correct destination.

**Comment by vanadiscrawford** [comment]
Thank you for your comments.  Cloud Foundry Enterprise Environment has been deprecated and no additional documentation updates will be made at this time.
